### PR TITLE
add #include <cstdlib>

### PR DESCRIPTION
**Pull request by PedroCardoso**
Required to compile in Debian

### CODE REVIEW

**Comment by PedroCardoso** [comment]
Once merged, could you create a new version for pypi ? thanks

**Comment by chezou** [comment]
Thanks! I'll update pypi :)

**Comment by chezou** [comment]
I bumped it up! https://pypi.python.org/pypi/kytea/0.1.1

**Comment by PedroCardoso** [comment]
Was off for a while.
It seems you missed the file mykytea.hpp in pypi package.

**Comment by chezou** [comment]
Thanks for your comment.
I've fixed and bumped it. 87aba18707507d985ec4e19d66ab544031d0c846

**Comment by PedroCardoso** [comment]
Looks good. Thanks

**Pull request merged**
